version: '3.4'

services:
  idfiwallet:
    image: idfiwallet
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 9998:9998
